In [50]:
import pandas as pd
import csv

In [41]:
deaths=pd.read_csv('deaths.tsv', sep='\t')

In [42]:
len(deaths.columns.values[4:])

53

In [45]:
deaths["total"] = ""
for i, col in enumerate(deaths.columns.values[4:57]):
    deaths["total"][i] = sum(deaths[col])

/home/vmor/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [59]:
deaths["dates"] = ""
for i in range(len(deaths.columns.values[4:-1])):
    deaths["dates"][i] = deaths.columns.values[4:-1][i]

/home/vmor/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [65]:
total_death = deaths[["total", "dates"]]

In [66]:
total_death = total_death[total_death["total"] != ""]

In [67]:
total_death

   total      dates
0     17  1/22/2020
1     18  1/23/2020
2     26  1/24/2020
3     42  1/25/2020
4     56  1/26/2020
5     82  1/27/2020
6    131  1/28/2020
7    133  1/29/2020
8    171  1/30/2020
9    213  1/31/2020
10   259   2/1/2020
11   362   2/2/2020
12   426   2/3/2020
13   492   2/4/2020
14   564   2/5/2020
15   634   2/6/2020
16   719   2/7/2020
17   806   2/8/2020
18   906   2/9/2020
19  1013  2/10/2020
20  1113  2/11/2020
21  1118  2/12/2020
22  1371  2/13/2020
23  1523  2/14/2020
24  1666  2/15/2020
25  1770  2/16/2020
26  1868  2/17/2020
27  2007  2/18/2020
28  2122  2/19/2020
29  2247  2/20/2020
30  2251  2/21/2020
31  2458  2/22/2020
32  2469  2/23/2020
33  2629  2/24/2020
34  2708  2/25/2020
35  2770  2/26/2020
36  2814  2/27/2020
37  2872  2/28/2020
38  2941  2/29/2020
39  2996   3/1/2020
40  3085   3/2/2020
41  3160   3/3/2020
42  3254   3/4/2020
43  3348   3/5/2020
44  3460   3/6/2020
45  3558   3/7/2020
46  3802   3/8/2020
47  3988   3/9/2020
48  4262  3/10/2020
49  4615  3/11/2020
50  4720  3/12/2020
51  5404  3/13/2020
52  5819  3/14/2020

In [70]:
media = pd.read_csv('media_numbers.tsv', sep='\t')

In [73]:
total_death["media"] = media["News Articles Published"]

In [74]:
total_death

   total      dates  media
0     17  1/22/2020     37
1     18  1/23/2020     96
2     26  1/24/2020     45
3     42  1/25/2020    308
4     56  1/26/2020    679
5     82  1/27/2020    503
6    131  1/28/2020    392
7    133  1/29/2020    160
8    171  1/30/2020    491
9    213  1/31/2020    355
10   259   2/1/2020    557
11   362   2/2/2020   1116
12   426   2/3/2020   1747
13   492   2/4/2020   1159
14   564   2/5/2020   1350
15   634   2/6/2020   3885
16   719   2/7/2020  10447
17   806   2/8/2020  14158
18   906   2/9/2020  17253
19  1013  2/10/2020  18422
20  1113  2/11/2020  10381
21  1118  2/12/2020  12598
22  1371  2/13/2020  21762
23  1523  2/14/2020  26582
24  1666  2/15/2020  28748
25  1770  2/16/2020  34210
26  1868  2/17/2020  31925
27  2007  2/18/2020  15833
28  2122  2/19/2020  17267
29  2247  2/20/2020  28135
30  2251  2/21/2020  29730
31  2458  2/22/2020  28534
32  2469  2/23/2020  27908
33  2629  2/24/2020  27002
34  2708  2/25/2020  13600
35  2770  2/26/2020  13653
36  2814  2/27/2020  27251
37  2872  2/28/2020  29072
38  2941  2/29/2020  29059
39  2996   3/1/2020  31899
40  3085   3/2/2020  27034
41  3160   3/3/2020  14241
42  3254   3/4/2020  14699
43  3348   3/5/2020  24688
44  3460   3/6/2020  28893
45  3558   3/7/2020  24879
46  3802   3/8/2020  23508
47  3988   3/9/2020  25549
48  4262  3/10/2020  15196
49  4615  3/11/2020  18472
50  4720  3/12/2020  38643
51  5404  3/13/2020  46046
52  5819  3/14/2020  54784

In [69]:
total_death.to_csv('cumu_deaths.csv')